name: DEV Deploy Doddle WAS

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build --no-cache -t doddle_be_dev:latest .

    - name: Deploy container locally
      run: |
        IMAGE=doddle_be_dev:latest
        docker stop BE_DEV || true
        docker rm BE_DEV || true
        docker run -d --name BE_DEV -p 25122:8000 \
          -e DATABASE_BACKEND=${{ secrets.DATABASE_BACKEND }} \
          -e DATABASE_CON2BACK=${{ secrets.DATABASE_CON2BACK }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
          -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
          -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
          -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
          -e SMTP_SERVER=${{ secrets.SMTP_SERVER }} \
          -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
          -e SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} \
          -e SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }} \
          -e CONTROL_HOST=${{ secrets.CONTROL_HOST }} \
          -e CONTROL_PORT=${{ secrets.CONTROL_PORT_DEV }} \
          $IMAGE
        docker system prune -af